// Bloco try catch
// Pode ser útil para debug
// O try catch não para o programa e sim o escopo onde se localiza

//let b = 2

try {

    let a = 2 + b
} catch(e) {

    console.log(e)
}

console.log("teste")